dist: bionic
sudo: required
services:
  - docker
language: bash

branches:
  only:
  - master

env:
  - IMAGE_NAME=12306_code_server DOCKER_CLI_EXPERIMENTAL=enabled

addons:
  apt:
    packages:
      - docker-ce

install:
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - chmod +x qemu/qemu-aarch64-static && chmod +x qemu/qemu-arm-static

script:
  - |
    # 构建docker镜像
    IMAGE_ARCH="amd64 arm32v7 arm64v8"
    COMMIT_SHA=$(git log -1 --pretty=format:"%H")
    LATEST_TAG_SHA=$(git rev-list --tags --max-count=1)

    for THIS_ARCH in ${IMAGE_ARCH}; do
      docker build -t $IMAGE_NAME:$THIS_ARCH \
      -f docker/$THIS_ARCH-Dockerfile .
      if [ $COMMIT_SHA == $LATEST_TAG_SHA ]; then
        docker tag $IMAGE_NAME:$THIS_ARCH $IMAGE_NAME:$THIS_ARCH-$(git describe --abbrev=0 --tags)
      fi
    done
    
    # 推送镜像到docker hub
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      for THIS_ARCH in ${IMAGE_ARCH}; do
        #  标记镜像
        docker tag $IMAGE_NAME:$THIS_ARCH $DOCKER_USERNAME/$IMAGE_NAME:$THIS_ARCH
        if [ $COMMIT_SHA == $LATEST_TAG_SHA ]; then
          docker tag $DOCKER_USERNAME/$IMAGE_NAME:$THIS_ARCH $DOCKER_USERNAME/$IMAGE_NAME:$THIS_ARCH-$(git describe --abbrev=0 --tags)
        fi
      done
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push $DOCKER_USERNAME/$IMAGE_NAME
      docker manifest create $DOCKER_USERNAME/$IMAGE_NAME:latest $DOCKER_USERNAME/$IMAGE_NAME:amd64 $DOCKER_USERNAME/$IMAGE_NAME:arm32v7 $DOCKER_USERNAME/$IMAGE_NAME:arm64v8
      docker manifest inspect $DOCKER_USERNAME/$IMAGE_NAME:latest
      docker manifest push $DOCKER_USERNAME/$IMAGE_NAME:latest
      if [ $COMMIT_SHA == $LATEST_TAG_SHA ]; then
        TAG=$(git describe --abbrev=0 --tags)
        docker manifest create $DOCKER_USERNAME/$IMAGE_NAME:$TAG $DOCKER_USERNAME/$IMAGE_NAME:amd64 $DOCKER_USERNAME/$IMAGE_NAME:arm32v7 $DOCKER_USERNAME/$IMAGE_NAME:arm64v8
        docker manifest inspect $DOCKER_USERNAME/$IMAGE_NAME:$TAG
        docker manifest push $DOCKER_USERNAME/$IMAGE_NAME:$TAG
      fi
    fi